# HTTP
quarkus.http.port=8080

# OIDC / Keycloak
quarkus.oidc.auth-server-url=http://localhost:8080/realms/glow-realm
quarkus.oidc.client-id=glow-payment-service
quarkus.oidc.credentials.secret=<your-client-secret>
    # The client secret can be found in the Keycloak admin console under:
    # glow-realm > Clients > glow-user-service > Credentials -> Client Secret

# Stripe
glow.payment.stripe.secret-key=${STRIPE_SECRET_KEY:}
glow.payment.stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:}

# Kafka – disabled for now, until glow-devops is updated
# mp.messaging.incoming.words-in.auto.offset.reset=earliest
# mp.messaging.incoming.words-in.topic=words
# mp.messaging.outgoing.words-out.topic=words
